### ISSUE TITLE
MessageChannelAdapter leaks event listeners

### ISSUE THREAD

**Issue by sqs** [GoogleChromeLabs/comlink#267]
The MessageChannelAdapter has a leak. If it is used to transfer a MessagePort, a new event listener is added that never gets cleaned up (because `smc.addEventListener` is called but `smc.removeEventListener` is never called). Depending on the usage pattern, this can mean that the array of event listeners grows very quickly and has a significant performance impact on the page.

I saw the `v4` branch removes the MessageChannelAdapter. Do you have a solution to this problem in mind in `v4`?

I was prototyping a way to monkey-patch `MessagePort#close` to send closed notifications and perform cleanup, to solve this problem. Does that sound like the right solution to you?

(Not directly related to #63, but that also talks about GCing MessagePorts.)

**Comment by surma** [comment]
I removed `MessageChannelAdapter` because it was a hack rather than something that should be officially part of this library (and me not caring about leaks was part of that 😅).

The old `MessageChannelAdapter` should still work with v4, but I do wanna write something better _at some point_. It’s not a priority right now to be honest.

Sending an event for `close()` sounds reasonable! If you end up writing something that is better, I’d be happy to link it from the README.
