### ISSUE TITLE
Workly

### ISSUE THREAD

**Issue by Finesse** [GoogleChromeLabs/comlink#288]
There is a similar package called [Workly](https://github.com/pshihn/workly). It also provides a simple API to work with a class in a WebWorker and even simpler to use.

<table>
<thead>
<tr><th>Comlink</th><th>Workly</th></tr>
</thead>
<tbody>
<tr>
<td>

```js
// main.js
import * as Comlink from "comlink";

const MyClass = Comlink.wrap(
  new Worker("worker.js")
);

const instance = await new MyClass();
await instance.logSomething();
```

```js
// worker.js
import * as Comlink from "comlink";

const myValue = 42;
class MyClass {
  logSomething() {
    console.log(`myValue=${myValue}`);
  }
}
Comlink.expose(MyClass);
```

</td>
<td>

```js
import * as workly from "workly";

const MyClass = workly.proxy(class {
  myValue = 42;
  logSomething() {
    console.log(`myValue=${this.myValue}`);
  }
});

const instance = await new MyClass();
await instance.logSomething();
```
There is also an expose API in Workly but it isn't required for this example

</td>
</tr>
</tbody>
</table>

What are the differences and advantages of Comlink over Workly?

**Comment by surma** [comment]
Workly seems to share a suspicious amount of code with Comlink, but that might just be a coincidence.

The API you have on the right is stringifying the class to send it to a worker and then calls `eval()` or similar. That’s pretty much what I did in [Clooney](https://github.com/GoogleChromeLabs/clooney), which uses Comlink under the hood.

That all being said, in my experience I didn’t find the stringification approach really useful in real apps. Apart from the unnecessary double-parsing and CSP violation, it breaks with some minifiers and bundlers due to the fact that the classes is lexically sharing a scope but in reality they do not (due to the stringification). So certain optimizations are applied that are not correct with what’s happening when the code is actually run.

I am not trying to deter you from using Workly (or Clooney 😄), it could be just what you need. Comlink is definitely more generalized and extensible.
