### ISSUE TITLE
Provide Example of worker A calling Worker B via MessagePort/Comlink

### ISSUE THREAD

**Issue by femski** [GoogleChromeLabs/comlink#294]
How do you send MessagePort for a proxy to a 2nd Worker thread (so the 2nd worker call 1st Worker directly without having to go through main thread) ?

Main thread:

// create two workers
const aProxy = Comlink.wrap(new "aWorker.js));
const bProxy = Comlink.wrap(new "bWorker.js));

// sent MessagePort of 1st Worker to 2nd Worker

const aPort = await aProxy [ Comlink.createEndpoint ] ();
bProxy.setRemotePort(Comlink.transfer(aPort, [aPort]);

in bWorker:

// 2nd worker tries to call 1st Worker via MesagChannel

setRemotePort(aPort:MessagePort){
     this.aProxy = (await Comlink.wrap(aPort));
     // test here...
     let result = await aProxy.aMethod(param1, param2, ...);
}

Exception thrown in bWorker is:
Uncaught (in promise) TypeError: Cannot read property 'apply' of undefined

It seems MessagePort wasn't property transferred or there is typecasting issue somewhere.

**Comment by femski** [comment]
It seems you have to call createEndpoint on the instance of the proxy - not the proxy interface itself.

This worked:
aInstance = new aProxy();

aPort: await aInstance[Comlink.createEndpoint]()

....

**Comment by celluj34** [comment]
Do you a complete example of this? Event with your update I don't understand what changes I would need to make.

Things I am confused about:
* I can't create a new instance of my `aProxy`, because I want a worker, not a local instance
* Comlink,wrap doesn't return a promise, so awaiting it does nothing
* Are you still calling transfer? I've read the docs but passing in the entire object in the second parameter doesn't make sense to me

Please let me know if you have any additional code
