### ISSUE TITLE
class instance callback functions, and callbacks without Comlink.proxy

### ISSUE THREAD

**Issue by benbenbenbenbenben** [GoogleChromeLabs/comlink#426]
We've forked and made a small change to enable automatic `Comlink.proxy` calls on arguments that answer `true` to `typeof(arg) === function` and without testing in the wild this seems to solve our immediate issue with class instance methods not proxying, as well as giving us the bonus of no longer needing envelope callbacks with `Comlink.proxy()`.

Is this something the project would like to have?

Save creating the pull request, here is our fork: https://github.com/dcdc-io/comlink

Does Comlink want *this* feature or should we go it alone with this change?

**Comment by surma** [comment]
Hey @benbenbenbenbenben,

I know that this is sometimes desirable, but since every proxied function creates a MessagePort pair, it can be a bit unpredictable when it comes to performance. That’s why I want proxying to be explicit by default.

That being said, this is one of the major reasons I added [TransferHandlers](https://github.com/GoogleChromeLabs/comlink#transfer-handlers-and-event-listeners). If you add this transfer handler on both the main thread and the worker, functions will be proxied automatically :) No need to fork/patch Comlink. Hope that helps!

```js
Comlink.transferHandlers.set("FUNCTION", {
  canHandle: obj => typeof obj === "function",
  serialize(obj) {
    const { port1, port2 } = new MessageChannel();
    Comlink.expose(obj, port1);
    return [port2, [port2]];
  },
  deserialize(port) {
    port.start();
    return Comlink.wrap(port);
  }
});
```

(Closing this. If you think this warrants further discussion, please feel free to re-open.)

**Comment by benbenbenbenbenben** [comment]
Thank you!
