### ISSUE TITLE
Terminating a worker doesn't resolve/reject pending promises

### ISSUE THREAD

**Issue by tzaitoun** [GoogleChromeLabs/comlink#428]
My worker does a lot of heavy computations and in my use case, if a user "imports a new project", I should terminate the worker and let the object that called the worker abort its future operations. Example:
```
async loadData() {
  // make fetch request
   return this.webworker.processData(data);
}
```
processData will never be resolved/rejected after I terminate the webworker. Is there any way around this or a better approach in cancelling webworkers.?

**Comment by tzaitoun** [comment]
I'm gonna ask in Stackoverflow, this is more of a question.

**Comment by gormonn** [comment]
@tzaitoun Do you find a way?

**Comment by gormonn** [comment]
now I am trying to proxy AbortController

**Comment by gormonn** [comment]
I did it.
In my case, all promises are axios requests.
I created AbortController in worker class
I threw it into axios inside the worker
And created a class method that calls controller.abort()

Just in case this didn't work, I was thinking of batching promises. Since inside the worker I recursively create trees from a large number of requests, up to three nested Promise.all are used there.

Hypothetically, batching would help with this, but the nature of recursion is such that it would not be so easy.

For batching I thought to use https://www.npmjs.com/package/async-batch
