### ISSUE TITLE
remove confusing `importScripts` from readme examples

### ISSUE THREAD

**Issue by a7madgamal** [GoogleChromeLabs/comlink#548]
I wanted to use this lib in a basic modern js setup (create-react-app) and implementing the examples was a bit confusing
```
importScripts("https://unpkg.com/comlink/dist/umd/comlink.js");
// importScripts("../../../dist/umd/comlink.js");
```
what is `importScripts`? why is the second line commented out?
unless I'm missing something we should replace this with a simple import statement because it's 2021 :D

**Comment by surma** [comment]
Nope, ES Modules are still not well supported in Workers.
![Screen Shot 2021-06-21 at 10 36 47](https://user-images.githubusercontent.com/234957/122741229-a8850680-d27c-11eb-9dbf-2b63970be642.png)

`importScripts()` is the normal, standard way of loading another script in a worker. You are using bundler (webpack) via `create-react-app`, which will convert your ES Module imports to `importScripts` during build time. 

These demos/examples are supposed to work without a bundler setup, which is why I’m using `importScripts()` directly. The second import is there in case you want to work on Comlink itself and test your local build rather than the one from unpkg.com.
