### ISSUE TITLE
Callbacks need to be wrapped in Comlink.proxy? Make it automatic instead?

### ISSUE THREAD

**Issue by trusktr** [GoogleChromeLabs/comlink#556]
Why is `Comlink.proxy` required to be used by the end user for callbacks? Can the generated classes call it internally inside their method when a function is passed in? And same with other scenarios?

For example, 

```js
  await remoteFunction(Comlink.proxy(callback));
```

would become

```js
  await remoteFunction(callback);
```

Obvious without proxying, there would be an error, because functions are not serializable.

I think the user experience would be more ergonomic this way.

Is there some reason the `Comlink.proxy` call needs to be on the outside?

**Comment by surma** [comment]
Every `Comlink.proxy()` creates a new `MessagePort` pair and keeps the exposed object alive. This can lead to some nasty leaks and unexpected behavior, so it shouldn’t be happening by default. So that’s why I decided that you need to explicitly proxy.

That being said, if you want to do it automatically, you can write a `TransferHandler` that proxies all functions automatically **but use it with care**.

```js
// Both in worker and main thread
Comlink.transferHandlers.set("FUNC", {
  canHandle: (obj) => typeof obj === "function",
  serialize: (obj) => {
    const { port1, port2 } = new MessageChannel();
    Comlink.expose(obj, port1);
    return [port2, [port2]];
  },
  deserialize: (port) => {
    return Comlink.wrap(port);
  },
});

// Worker
Comlink.expose({
  sayHello(cb) {
    cb("lol");
  },
});

// Main
const api = Comlink.wrap(worker);
// Just works
api.sayHello((v) => log(v));
```

**Comment by sisou** [comment]
With the WeakRefs' FinalizationRegistry (which is pretty well supported by now), will these auto-created proxies be cleaned up when they are GC'd?

**Comment by surma** [comment]
Yes
