### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by Snugug** [GoogleChromeLabs/comlink#568]
I'm currently using Vite to build a webapp, which has its own [web worker handling](https://vitejs.dev/guide/features.html#web-workers) (which, as far as I can tell, uses `{type: 'module'}` in development to work without needing to compile a workers and does the actual compile in production, but otherwise is the result of `new Worker()`). This is to say, my worker is currently written as an ES Module.

In my main-thread script, I've got the following:

```js
import myWorker from '$workers/my-worker?worker';
import * as Comlink from 'comlink';

const worker = new myWorker();
const wrapped = Comlink.wrap(worker);
```

In my worker, I've got this:
```js
import * as Comlink from 'comlink';

function doStuff(arg1, arg2) {
  // …
}

Comlink.expose(doStuff);
```

Both of these seem to work fine. However, when I try and call my wrapped function, `wrapped.doStuff('foo', 'bar');`, I get an error thrown from `expose` (line 312 in comlink.ts, specifically `returnValue = rawValue.apply(parent, argumentList);` for `MessageType.APPLY`), ` Cannot read properties of undefined (reading 'apply')`. Stepping through my code, `parent` is the correct function, the argument list is correct, but `rawValue` is `undefined`. I'm not sure why everything seems to be right except that, and why it's failing there.

Any help would be greatly appreciated!

**Comment by Snugug** [comment]
I've fixed it; I was exporting multiple items, and called `Comlink.expose` twice instead of exposing an object. Exposing an object resolves the issue. It wasn't clear to me that I couldn't call `expose` more than once like I with `module.exports` or ESM `export`

**Comment by kalzoo** [comment]
I ran into this as well, without multiple calls to `expose`. In my case, it was because of a typo in the name of the function I was calling. If the error message were more clear, it may have saved me a little time in resolution. [this line](https://github.com/GoogleChromeLabs/comlink/blob/dffe9050f63b1b39f30213adeb1dd4b9ed7d2594/src/comlink.ts#L314) tries to look up the called object property; if missing, it returns undefined, which - IMO - should raise a clear error right out instead of this issue's title.

Happy to send a simple PR to that effect if welcome.
