### ISSUE TITLE
proxyValues inside of argument objects are not serialized correctly

### ISSUE THREAD

**Issue by wmhilton** [GoogleChromeLabs/comlink#59]
Problem: proxyValues inside of argument objects do not work.

Example:
```js
  // Here "git" is a Comlink remote object
  function handleProgress (e) {
    store.progress[owner + '/' + name] = e.loaded / e.total
    update()
  }
  return git.clone({
    dir,
    depth: 1,
    ref,
    onprogress: Comlink.proxyValue(handleProgress),
    url: repo
  })
```

Expected: the handleProgress callback would be called.

Actual:
```
client.js:165 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'MessagePort': function handleProgress (e) {
    store.progress[owner + '/' + name] = e.loaded / e.total
    update()
  } could not be cloned.
```

Suggested Solution: Automatically wrap anything that throws a "could not be cloned" error in a ProxyValue. Then callbacks everywhere should Just Work (TM).

**Comment by surma** [comment]
Sorry for the late reply!

The function is proxied correctly. The problem here is the event object that is a parameter to the function. Events are not transferable. Take a look a the [EventListener example](https://github.com/GoogleChromeLabs/comlink/tree/master/docs/examples/eventlistener) to see how you can make it work :)
