### ISSUE TITLE
Document browser compatibility

### ISSUE THREAD

**Issue by dvoytenko** [GoogleChromeLabs/comlink#72]
Could you please document the browser compatibility, in terms of major dependencies. E.g. is full ES2015 Proxy support required? Is there a way, when using a polyfill, to pre-enumerate known properties?

**Comment by surma** [comment]
I have added a list of compatible browsers (forgot to close this issue, sorry). I have not tested Comlink with a ES6 proxy polyfill. Might work, might not work.

**Comment by adrianromanko** [comment]
@surma What would you say to converting this to using babel + core-js and lower the browser requirements?

**Comment by surma** [comment]
Is there a particular browser that you want to support?  Because, as I said, the limiting factor is ES6 proxies, and support for that is looking fairly good!

<img width="1296" alt="screen shot 2018-03-05 at 8 25 09 pm" src="https://user-images.githubusercontent.com/234957/36998056-949467e8-20b3-11e8-917d-c25729092507.png">

AFAIR, everything else is in Comlink fairly stable and old tech.

**Comment by adrianromanko** [comment]
Thanks.
I would like to get it down to Chrome version 43. Not sure if Proxies cannot be transpiled or polyfilled with ES5.

**Comment by surma** [comment]
There is a [polyfill for proxies](https://github.com/GoogleChrome/proxy-polyfill). If you want give it a try and let me know how it goes. 

If I don’t have to mangle my code to make it work, I’m happy to support Chrome 43.

**Comment by adrianromanko** [comment]
Works with the Proxy polyfill.
es5 fork: https://github.com/adrianromanko/comlink

**Comment by surma** [comment]
Cooool! No further changes necessary? If so I’ll put a comment in the README :)
